/*
 * generated by Xtext 2.25.0
 */
package org.healthydrone.dsl.expressions.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class ExpressionsWebModule extends AbstractExpressionsWebModule {
}
