/*
 * generated by Xtext 2.26.0.RC1
 */
package org.healthydrone.dsl.expressions.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class ExpressionsWebModule extends AbstractExpressionsWebModule {
}
