/*
 * generated by Xtext 2.26.0.RC1
 */
package org.healthydrone.dsl.expressions.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class ExpressionsProposalProvider extends AbstractExpressionsProposalProvider {
}
