/*
 * generated by Xtext 2.26.0.RC1
 */
package org.healthydrone.dsl.expressions.ide


/**
 * Use this class to register ide components.
 */
class ExpressionsIdeModule extends AbstractExpressionsIdeModule {
}
