/*
 * generated by Xtext 2.25.0
 */
package org.healthydrone.dsl.expressions.ide;


/**
 * Use this class to register ide components.
 */
public class ExpressionsIdeModule extends AbstractExpressionsIdeModule {
}
