/*
 * generated by Xtext 2.26.0.RC1
 */
package org.healthydrone.dsl.expressions.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class ExpressionsScopeProvider extends AbstractExpressionsScopeProvider {

}
