/*
 * generated by Xtext 2.26.0.RC1
 */
package org.xtext.example.mydsl.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
class MyDslOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
