/*
 * generated by Xtext 2.26.0.RC1
 */
package org.healthydrone.dsl.expressions.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class ExpressionsUiModule extends AbstractExpressionsUiModule {
}
