/*
 * generated by Xtext 2.26.0.RC1
 */
package org.healthydrone.dsl.expressions


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ExpressionsRuntimeModule extends AbstractExpressionsRuntimeModule {
}
