/*
 * generated by Xtext 2.26.0.RC1
 */
package org.healthydrone.dsl.expressions


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ExpressionsStandaloneSetup extends ExpressionsStandaloneSetupGenerated {

	def static void doSetup() {
		new ExpressionsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
